# Supercompressible: optimization 3d

This notebook intends to show the optimization process to maximize the absorbed energy in the 3D case. 

So, let's start by importing the required libraries:

In [1]:
# standard library
import pickle

# third-party
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score
from sklearn.gaussian_process.kernels import Matern
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.svm import SVC
from scipy.optimize import minimize
from matplotlib.colors import ListedColormap

Now, let's import the data.

In [2]:
# get pandas frame
filename = 'DoE_results.pkl'
with open(filename, 'rb') as file:
    data = pickle.load(file)
points = data['points']
print('variables:', [col for col in points.columns])

# get number of inputs
n_inputs = len(points.columns) - 3

# get X data
X = points.iloc[:,range(n_inputs)].values
X_full = points.iloc[:,range(n_inputs)].values

# get energy data
var_name = 'energy'
y = points.loc[:, var_name].values

# get coilable data
class_name = 'coilable'
y_class = points.loc[:, class_name].values

print('X:', X)
print('X shape:', np.shape(X))
print('y:', y)
print('y shape:', np.shape(y))
print('y_class:', y_class)
print('y_class shape:', np.shape(y_class))

variables: ['ratio_d', 'ratio_pitch', 'ratio_top_diameter', 'coilable', 'sigma_crit', 'energy']
X: [[0.004      0.25       0.        ]
 [0.0385     0.875      0.4       ]
 [0.05575    0.5625     0.2       ]
 ...
 [0.06037836 1.08930969 0.58618164]
 [0.04312836 0.77680969 0.38618164]
 [0.00862836 1.40180969 0.78618164]]
X shape: (10000, 3)
y: [2.79529996e-04            nan 1.42853201e+01 ...            nan
            nan            nan]
y shape: (10000,)
y_class: [1. 0. 2. ... 0. 2. 0.]
y_class shape: (10000,)


The variables ```X``` and ```y``` contain all the data. Nevertheless, there's ```NaN``` values that cannot be considered.

In [3]:
for yy in np.unique(y_class):
    print('Class %i: %i' % (int(yy), np.sum(y_class==yy)))

Class 0: 3174
Class 1: 2013
Class 2: 4813


In [4]:
# missing indices
indices = pd.notnull(points.loc[:, var_name]).values

# get matching energy and coiling data
y = points.loc[indices, var_name].values
# y_class = points.loc[indices, class_name].values

# get X data
X = points.iloc[indices,range(n_inputs)].values

print('X:', X)
print('X shape:', np.shape(X))
print('y:', y)
print('y shape:', np.shape(y))
print('y_class:', y_class)
print('y_class shape:', np.shape(y_class))

X: [[0.004      0.25       0.        ]
 [0.05575    0.5625     0.2       ]
 [0.0686875  0.328125   0.55      ]
 ...
 [0.06900336 0.30805969 0.68618164]
 [0.03450336 0.93305969 0.28618164]
 [0.02587836 0.46430969 0.18618164]]
X shape: (5264, 3)
y: [2.79529996e-04 1.42853201e+01 3.99711660e+01 ... 5.35333775e+01
 2.35352031e+00 6.15239445e-01]
y shape: (5264,)
y_class: [1. 0. 2. ... 0. 2. 0.]
y_class shape: (10000,)


Let's now clean the data.

In [5]:
def perform_cleaning(X, y, n_std_cleaning):
    
    # compute threshold
    y_mean, y_std = np.mean(y), np.std(y)
    y_thresh = y_mean + n_std_cleaning * y_std

    # indices
    print(y_thresh)
    indices = np.where(y < y_thresh)
    n_dismissed_points = len(y) - len(indices[0])
    print('Dismissed points:', n_dismissed_points)

    # X and y
    y = y[indices]
    X = X[indices]
    print(np.shape(y))
    print(np.shape(X))

    return X, y, n_dismissed_points

In [6]:
n_std_cleaning = 5  # dismiss points that fall outside this range

n_dismissed_points = 1
while n_dismissed_points > 0:
    X, y, n_dismissed_points = perform_cleaning(X, y, n_std_cleaning)

251.41209785647746
Dismissed points: 6
(5258,)
(5258, 3)
78.83845527943124
Dismissed points: 7
(5251,)
(5251, 3)
76.83459344264611
Dismissed points: 0
(5251,)
(5251, 3)


Methods to create and evaluate the regression and classification models.

In [7]:
def make_gp_regression(X_train, y_train, kernel):
    
    # train model
    model = GaussianProcessRegressor(kernel=kernel, alpha=0.1**2, 
                                   n_restarts_optimizer=0)
    model.fit(X_train, y_train)
    
    return model

In [8]:
def split_data(X, y, train_size):
    
    # split data
    test_size = 1 - train_size
    indices = range(len(y))
    X_train = X[indices[:-int(round(len(indices) * test_size))]]
    X_test = X[indices[-int(round(len(indices) * test_size)):]]
    y_train = y[indices[:-int(round(len(indices) * test_size))]]
    y_test = y[indices[-int(round(len(indices) * test_size)):]]
    
    return (X_train, X_test, y_train, y_test)

In [9]:
def evaluate_model(model, X_test, y_mean_test, n_train):
    
    # predict test
    y_mean_pred = model.predict(X_test, return_std=False)

    # error metrics
    mse = mean_squared_error(y_mean_test, y_mean_pred)
    r2 = r2_score(y_mean_test, y_mean_pred)
    expl_var = explained_variance_score(y_mean_test, y_mean_pred)
    print("The mean squared error is %0.3e" % mse)
    print("The R2 score is %0.3f" % r2)
    print("The explained variance score is %0.3f" % expl_var)

    # plot predicted vs observed
    plt.figure()
    plt.plot(y_mean_test, y_mean_pred, 'o')
    plt.plot([np.min(y_mean_test), np.max(y_mean_test)], [np.min(y_mean_test), np.max(y_mean_test)], 'r-')
    plt.title('Posterior kernel: %s\n$n_{train} = %i$, $R^{2} = %0.3f$, $ MSE = %0.3e$' % (model.kernel_, n_train, r2, mse))
    plt.ylabel("Predicted")
    plt.xlabel("Observed")
    plt.show()

In [10]:
def evaluate_clf_model(clf, train_data, test_data, metrics=((accuracy_score, 'Accuracy classification score'),), print_results=True):
    
    # make predictions
    y_train_predicted = clf.predict(train_data[0])
    y_test_predicted = clf.predict(test_data[0])
    
    metric_results = []
    for Imetric in range(np.shape(metrics)[0]):
        metric = metrics[Imetric][0] # select metric used
        metric_results.append([metric(train_data[1], y_train_predicted), metric(test_data[1], y_test_predicted)])
        
        if print_results:
            print("Train", metrics[Imetric][1],"for ML model:", metric_results[-1][0])
            print("Test", metrics[Imetric][1],"for ML model:", metric_results[-1][1])
        
    return metric_results

Next, we will prepare the classification.

In [11]:
# choose train size
train_size = .8
(X_train, X_test, y_train, y_test) = split_data(X_full, y_class, train_size)
n_train = len(X_train)

# scale data
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# train
clf = SVC(kernel='rbf').fit(X_train_scaled, y_train)

# evaluate model
evaluate_clf_model(clf, (X_train_scaled, y_train), (X_test_scaled, y_test));

Train Accuracy classification score for ML model: 0.89025
Test Accuracy classification score for ML model: 0.8895


In [12]:
xx = [[0.04276196, 0.41448975, 0.69628906], # best in full dataset
      [0.03954443, 0.51306152, 0.65351563],  # best in full dataset (N=3000)
      [0.0337832, 0.32080078, 0.7578125],  # best in full dataset (N=1000)
      [0.03710181, 0.26312256, 0.77441406], # best in the dataset after classification with N=10000
      [0.02876318, 0.31774902, 0.72851562], # best in the dataset after classification with N=5000
      [0.0337832,  0.32080078, 0.7578125], # best in the dataset after classification with N=3000 and N=1000
      [0.04, 0.417, 0.8], # best found after after classification and regression with N=10000
      [0.038, 0.32, 0.8], # best found after after classification and regression with N=5000
      [0.037, 0.32, 0.8], # best found after after classification and regression with N=3000
      [0.037, 0.4, 0.8], # best found after after classification and regression with N=1000
      ]
yy = clf.predict(scaler.transform(xx))

print(yy)

[2. 2. 1. 1. 1. 1. 1. 1. 1. 1.]


In [13]:
# choose train size
train_size = .1
(X_train, X_test, y_train, y_test) = split_data(X, y, train_size)
n_train = len(X_train)

# scale data
# scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# train and predict
kernel = 1.0 * Matern(length_scale=1.0, nu=2.5, length_scale_bounds=(1e-1, 10.0))
model = make_gp_regression(X_train_scaled, y_train, kernel)

# evaluate model
# evaluate_model(model, X_test_scaled, y_test, n_train)

In [14]:
xx = [[0.04276196, 0.41448975, 0.69628906]]
yy = clf.predict(scaler.transform(xx))
yyen = model.predict(scaler.transform(xx))

print(xx)
print(yy)
print(yyen)

[[0.04276196, 0.41448975, 0.69628906]]
[2.]
[9.94200963]


We now have our classification and regression model ready. We can use these functions to optimize for the absorbed energy while making sure that the coilability is favorable (class 1). We can do this by penalizing the other classes. A similar action can be undertaken when the input point does not fall within the bounds of the parameter space.

In [15]:
variables = ['ratio_d', 'ratio_pitch', 'ratio_top_diameter']
bounds = [data['doe_variables'][name] for name in variables]
print(bounds)
print()

def validitycheck(x):
    res = 0
    for i in range(3):
        a = bounds[i][0] <= x[0][i]
        b = x[0][i] <= bounds[i][1]
        c = clf.predict(scaler.transform(x)) == 1
        res += a + b + c
    if res == 9:
        return True
    else:
        return False

print(validitycheck([[0.04, 0.417, 0.8]]))
print()

def objfun(x):
    penalty = 1e5
    x = [list(x)]
    print(x)
    print(model.predict(scaler.transform(x)))
    print(clf.predict(scaler.transform(x)))
    print()
    if np.rint(clf.predict(scaler.transform(x))) == 1:
        output = -model.predict(scaler.transform(x))
    else:
        output = model.predict(scaler.transform(x))
        #output = penalty
    print(-output)
    print()
    return output
x0 = [[0.04, 0.417, 0.8]]
optval = minimize(objfun, x0=x0, method='Nelder-Mead') # Other optimization strategies available in the scipy docs
print(optval)

[[0.004, 0.073], [0.25, 1.5], [0.0, 0.8]]

True

[[0.04, 0.417, 0.8]]
[9.90978335]
[1.]

[9.90978335]

[[0.042, 0.417, 0.8]]
[12.11606059]
[2.]

[-12.11606059]

[[0.04, 0.43785, 0.8]]
[10.11323184]
[0.]

[-10.11323184]

[[0.04, 0.417, 0.8400000000000001]]
[11.11621244]
[0.]

[-11.11621244]

[[0.038, 0.4309, 0.8266666666666669]]
[8.77261587]
[0.]

[-8.77261587]

[[0.03866666666666666, 0.44016666666666665, 0.7777777777777777]]
[8.29955166]
[2.]

[-8.29955166]

[[0.03777777777777778, 0.4208611111111111, 0.8029629629629631]]
[7.9035549]
[1.]

[7.9035549]

[[0.03962962962962962, 0.4211185185185185, 0.7604938271604937]]
[8.63993472]
[2.]

[-8.63993472]

[[0.039222222222222214, 0.42356388888888885, 0.7770370370370371]]
[8.65187061]
[2.]

[-8.65187061]

[[0.03888888888888889, 0.41893055555555553, 0.8014814814814816]]
[8.86760321]
[1.]

[8.86760321]

[[0.03933333333333333, 0.4285833333333333, 0.7888888888888889]]
[9.07717182]
[2.]

[-9.07717182]

[[0.039, 0.42395, 0.8133333333333335]]
[9.329193